Marvel Api connection
mathleite/marvel-application-backend pull request #4
Opened 2019-10-11 18:59 UTC by silvaadriel

2019-10-12 01:03 UTC, mathleite requested changes

2019-10-12 01:03 UTC, mathleite commented on integrator/app/Services/MarvelApi/Characters.php
> +<?php
Is this file a *Controller*, right?

Another point, this file should not be in this folder. We will use the [Domain Design](https://medium.com/@ibrunotome/a-domain-driven-design-ddd-approach-to-the-laravel-framework-18906b3dd473). You can create the *Characters* path (inside *app* path) and put this file inside a `Controller` folder.

2019-10-12 01:03 UTC, mathleite commented on integrator/app/Services/MarvelApi/Characters.php
> +<?php
Don't forget, we need create the *rules* to our *controllers/requests*

2019-10-12 01:03 UTC, mathleite commented on integrator/app/Services/MarvelApi/Characters.php
> +<?php
We don't need to use the *resource* route anymore, because we have many *routes* to our requests now, right? Should you use *"grouped routes"* now!

[Routing - Laravel](https://laravel.com/docs/5.8/routing#route-group-prefixes).

2019-10-12 01:03 UTC, mathleite commented on integrator/app/Services/GuzzleHttpRequest.php
> +class GuzzleHttpRequest
Is this a *Service*, right?

Another point, this file should not be in this folder. We will use the [Domain Design](https://medium.com/@ibrunotome/a-domain-driven-design-ddd-approach-to-the-laravel-framework-18906b3dd473). You can create the *GuzzleHttpClient* path (inside *app* path) and put this file inside a `Service` folder.

2019-10-12 01:03 UTC, mathleite commented on integrator/app/Services/GuzzleHttpRequest.php
> +    protected function get($url)
This function will return an *array*, right? We need to use the [Type Hint](https://mlocati.github.io/articles/php-type-hinting.html)

2019-10-12 01:03 UTC, mathleite commented on integrator/app/Services/GuzzleHttpRequest.php
> +    protected function get($url)
```suggestion
    protected function get(string $url): array
```

2019-10-12 01:03 UTC, mathleite commented on integrator/app/Services/GuzzleHttpRequest.php
> +    public function __construct(Client $httpClient)
Do we really need this **__construct** ?
According [Guzzle PSR-7](http://docs.guzzlephp.org/en/stable/psr7.html) we don't need. What do you think about that?

2019-10-12 01:03 UTC, mathleite commented on integrator/app/Services/GuzzleHttpRequest.php
> +        $contents = json_decode($response->getBody()->getContents());
The PhpStorm is crazy!!
![image](https://user-images.githubusercontent.com/34130446/66692072-64e99500-ec71-11e9-9f30-c9ce9ae6d1e6.png)
You need to require a *ext-json* to make sure we don't have problems
![image](https://user-images.githubusercontent.com/34130446/66692086-8185cd00-ec71-11e9-949d-67d643d4a19f.png)
 You can read more [here](https://medium.com/@luis.barros.nobrega/ext-json-is-missing-in-composer-json-what-is-this-700a1fcad966).

2019-10-12 01:03 UTC, mathleite commented on integrator/app/Services/GuzzleHttpRequest.php
> +    protected function get($url)
You need add the [PHPDoc](https://docs.phpdoc.org/references/phpdoc/index.html) in **ALL** *functions/methods* like this:
![image](https://user-images.githubusercontent.com/34130446/66692212-8d25c380-ec72-11e9-99bd-02a734c4206b.png)

2019-10-12 01:10 UTC, mathleite commented on integrator/app/Services/GuzzleHttpRequest.php
> +class GuzzleHttpRequest
Since this is a *Service*, I recommend that you rename this file to `GuzzleHttpClientService`. What do you think?

2019-10-12 21:32 UTC, silvaadriel commented on integrator/app/Services/MarvelApi/Characters.php
> +<?php
Would it be better to create the controller using the **CLI**?
```suggestion
php artisan make:controller CharactersController
```

2019-10-12 22:41 UTC, mathleite commented on integrator/app/Services/MarvelApi/Characters.php
> +<?php
Yes for sure!!

2019-10-13 19:14 UTC, silvaadriel commented on integrator/app/Services/GuzzleHttpRequest.php
> +    public function __construct(Client $httpClient)
I think so.
Laravel will inject the GuzzleHttp instance registered in AppServiceProvider via **__construct**, see [here](https://laravel.com/docs/6.x/container).
Is there any other way to do this?

2019-10-13 19:23 UTC, silvaadriel commented on integrator/app/Services/GuzzleHttpRequest.php
> +class GuzzleHttpRequest
>  I recommend that you rename this file to GuzzleHttpClientService.
What do you think?

I agree with you, GuzzleHttpClientService is a good name.

> You can create the GuzzleHttpClient path (inside app path) and put this file inside a Service folder.

like this?
![php](https://user-images.githubusercontent.com/39961737/66720598-3dabd880-edd5-11e9-9da4-665cee1e6015.jpg)

2019-10-14 01:53 UTC, mathleite commented on integrator/app/Services/GuzzleHttpRequest.php
> +class GuzzleHttpRequest
Yeah!!, but the correct will be a `Service` *folder*, because this *GuzzleHttpClientService* file is a service, right?

2019-10-14 02:01 UTC, mathleite commented on integrator/app/Services/GuzzleHttpRequest.php
> +    public function __construct(Client $httpClient)
I don't know exactly, but, if you understand the *"why"* that we need, **do** that!!

2019-10-16 16:24 UTC, mathleite requested changes

2019-10-16 16:24 UTC, mathleite commented on integrator/app/GuzzleHttpClient/Service/GuzzleHttpClientService.php
> +    public function get($url): array
You can improve this name!

What we "`get()`" ?

2019-10-16 16:24 UTC, mathleite commented on integrator/app/GuzzleHttpClient/Service/GuzzleHttpClientService.php
> +            $response = $this->httpClient->request('GET', $url);
You can *create* a *function* to do this `request`

2019-10-16 16:24 UTC, mathleite commented on integrator/app/GuzzleHttpClient/Service/GuzzleHttpClientService.php
> +    public function get($url): array
Did you forget the *Type* for this `$url`

2019-10-16 16:24 UTC, mathleite commented on integrator/app/GuzzleHttpClient/Service/GuzzleHttpClientService.php
> +            $contents = json_decode($response->getBody()->getContents());
The same function will return the **request** *"contents"*

2019-10-16 16:26 UTC, mathleite requested changes

2019-10-16 16:26 UTC, mathleite commented on integrator/app/GuzzleHttpClient/Service/GuzzleHttpClientService.php
> +class GuzzleHttpClientService
You can *create* a *contract* **interface** to ensure our functionalities

2019-10-20 00:23 UTC, mathleite approved these changes

2019-10-20 00:23 UTC, merged